CREATE TABLE USERS (
    id SERIAL PRIMARY KEY,
    username VARCHAR(32) NOT NULL UNIQUE,
    email VARCHAR(64) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL,
    admin BOOLEAN DEFAULT false
);

CREATE TABLE SERIES (
    id SERIAL PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    airDate TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    inProduction BOOLEAN,
    tagline VARCHAR(255),
    image VARCHAR(255) NOT NULL,
    description TEXT,
    language VARCHAR(2) NOT NULL,
    network VARCHAR(64),
    homepage VARCHAR(255)
);

CREATE TABLE GENRES (
    id SERIAL,
    name VARCHAR(64) PRIMARY KEY NOT NULL
);

CREATE TABLE SERIES_GENRES (
    id SERIAL PRIMARY KEY,
    serieId INTEGER NOT NULL,
    genreName VARCHAR(64) NOT NULL,
    CONSTRAINT FK_SERIES_SERIE FOREIGN KEY (serieId) REFERENCES SERIES(id) ON DELETE CASCADE,
    CONSTRAINT FK_GENRES_GENRE FOREIGN KEY (genreName) REFERENCES GENRES(name) ON DELETE CASCADE
);

CREATE TABLE USERS_SERIES (
    id SERIAL PRIMARY KEY,
    userId INTEGER NOT NULL,
    CONSTRAINT FK_USERS_USER FOREIGN KEY (userId) REFERENCES USERS(id) ON DELETE CASCADE,
    serieId INTEGER NOT NULL,
    CONSTRAINT FK_SERIES_SERIE FOREIGN KEY (serieId) REFERENCES SERIES(id) ON DELETE CASCADE,
    state VARCHAR(64),
    rating INTEGER
);

CREATE TABLE SEASONS (
    id SERIAL PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    no INTEGER NOT NULL,
    airDate TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    overview TEXT,
    poster VARCHAR(64) NOT NULL,
    serie VARCHAR(255) NOT NULL,
    serieId INTEGER NOT NULL,
    CONSTRAINT FK_SEASON_SERIE FOREIGN KEY (serieId) REFERENCES SERIES(id) ON DELETE CASCADE
);

CREATE TABLE EPISODES (
    id SERIAL PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    no INTEGER NOT NULL,
    airDate TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    overview TEXT,
    season INTEGER NOT NULL,
    serie VARCHAR(255) NOT NULL,
    serieId INTEGER NOT NULL,
    CONSTRAINT FK_EPISODE_SERIE FOREIGN KEY (serieId) REFERENCES SERIES(id) ON DELETE CASCADE,
    CONSTRAINT FK_EPISODE_SEASON FOREIGN KEY (season) REFERENCES SEASONS(id) ON DELETE CASCADE
);

INSERT INTO
  users
    (id, username, email, password, admin)
  VALUES
    (1, 'admin', 'admin@example.org', '$2b$11$41KtMgqLNnTFNZoBt507M.X.5zYYzbKz382Y705e9Ov944MRMKEm6', true);

INSERT INTO
  users
    (id, username, email, password, admin)
  VALUES
    (2, 'siggastud', 'siggastud@simnet.is', '$2b$11$52Yw4vWn2M85sFjmjzblneeRjTO48LJf9rJ0Ayo4Tt/JGX9iZBfAy', false);
